version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/app/backend
      - ./butler_agent_pkg:/app/butler_agent_pkg
      - ./agents:/app/agents
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
